package com.soubu.crmproject.base.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Remind".
 */
@Entity(nameInDb = "Remind")
public class Remind {

    @Id(autoincrement = true)
    private Long id;
    private java.util.Date date;
    private Integer remind_state;
    private Integer complete_state;
    private String content;
    private String address;
    private String phone;

    @Generated
    public Remind() {
    }

    public Remind(Long id) {
        this.id = id;
    }

    @Generated
    public Remind(Long id, java.util.Date date, Integer remind_state, Integer complete_state, String content, String address, String phone) {
        this.id = id;
        this.date = date;
        this.remind_state = remind_state;
        this.complete_state = complete_state;
        this.content = content;
        this.address = address;
        this.phone = phone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Integer getRemind_state() {
        return remind_state;
    }

    public void setRemind_state(Integer remind_state) {
        this.remind_state = remind_state;
    }

    public Integer getComplete_state() {
        return complete_state;
    }

    public void setComplete_state(Integer complete_state) {
        this.complete_state = complete_state;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

}
