package com.soubu.crmproject.base.greendao;

import com.soubu.crmproject.utils.CharacterParser;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Staff".
 */
@Entity(nameInDb = "Staff")
public class Staff implements Serializable {

    @Id(autoincrement = true)
    private Long id;
    private String username;
    private String mobile;
    private String email;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;
    private String staff_id;

    @Generated
    public Staff() {
    }

    public Staff(Long id) {
        this.id = id;
    }

    @Generated
    public Staff(Long id, String username, String mobile, String email, java.util.Date createdAt, java.util.Date updatedAt, String staff_id) {
        this.id = id;
        this.username = username;
        this.mobile = mobile;
        this.email = email;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.staff_id = staff_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getStaff_id() {
        return staff_id;
    }

    public void setStaff_id(String staff_id) {
        this.staff_id = staff_id;
    }

    public String getLetter() {
        return Character.toString(CharacterParser.getInstance().getSelling(username).charAt(0)).toUpperCase();
    }
}
