package com.soubu.crmproject.base.greendao;

import com.soubu.crmproject.utils.CharacterParser;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Staff".
 */
@Entity(nameInDb = "Staff")
public class Staff {

    @Id(autoincrement = true)
    private Long id;
    private String nickname;
    private String username;
    private String department;
    private String position;
    private String mobile;
    private String email;
    private String employeeNumber;
    private String officeAddress;
    private Boolean activated;
    private java.util.Date activatedAt;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;
    private String staff_id;

    @Generated
    public Staff() {
    }

    public Staff(Long id) {
        this.id = id;
    }

    @Generated
    public Staff(Long id, String nickname, String username, String department, String position, String mobile, String email, String employeeNumber, String officeAddress, Boolean activated, java.util.Date activatedAt, java.util.Date createdAt, java.util.Date updatedAt, String staff_id) {
        this.id = id;
        this.nickname = nickname;
        this.username = username;
        this.department = department;
        this.position = position;
        this.mobile = mobile;
        this.email = email;
        this.employeeNumber = employeeNumber;
        this.officeAddress = officeAddress;
        this.activated = activated;
        this.activatedAt = activatedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.staff_id = staff_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmployeeNumber() {
        return employeeNumber;
    }

    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    public String getOfficeAddress() {
        return officeAddress;
    }

    public void setOfficeAddress(String officeAddress) {
        this.officeAddress = officeAddress;
    }

    public Boolean getActivated() {
        return activated;
    }

    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    public java.util.Date getActivatedAt() {
        return activatedAt;
    }

    public void setActivatedAt(java.util.Date activatedAt) {
        this.activatedAt = activatedAt;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getStaff_id() {
        return staff_id;
    }

    public void setStaff_id(String staff_id) {
        this.staff_id = staff_id;
    }

    public String getLetter(){
        return Character.toString(CharacterParser.getInstance().getSelling(nickname).charAt(0)).toUpperCase();
    }

}
