package com.soubu.crmproject.base.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "User".
 */
@Entity(nameInDb = "User")
public class User {

    @Id(autoincrement = true)
    private Long id;
    private String nickname;
    private String username;
    private String loginname;
    private String department;
    private String position;
    private String mobile;
    private String email;
    private String token;
    private String employeeNumber;
    private String officeAddress;
    private String note;
    private String pwd;
    private Boolean activated;
    private java.util.Date activatedAt;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;
    private String user_id;

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, String nickname, String username, String loginname, String department, String position, String mobile, String email, String token, String employeeNumber, String officeAddress, String note, String pwd, Boolean activated, java.util.Date activatedAt, java.util.Date createdAt, java.util.Date updatedAt, String user_id) {
        this.id = id;
        this.nickname = nickname;
        this.username = username;
        this.loginname = loginname;
        this.department = department;
        this.position = position;
        this.mobile = mobile;
        this.email = email;
        this.token = token;
        this.employeeNumber = employeeNumber;
        this.officeAddress = officeAddress;
        this.note = note;
        this.pwd = pwd;
        this.activated = activated;
        this.activatedAt = activatedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.user_id = user_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getLoginname() {
        return loginname;
    }

    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getEmployeeNumber() {
        return employeeNumber;
    }

    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    public String getOfficeAddress() {
        return officeAddress;
    }

    public void setOfficeAddress(String officeAddress) {
        this.officeAddress = officeAddress;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public Boolean getActivated() {
        return activated;
    }

    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    public java.util.Date getActivatedAt() {
        return activatedAt;
    }

    public void setActivatedAt(java.util.Date activatedAt) {
        this.activatedAt = activatedAt;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

}
